language: java
jdk:
- oraclejdk8
before_install:
- openssl aes-256-cbc -K $encrypted_37c734d3f559_key -iv $encrypted_37c734d3f559_iv
  -in src/main/resources/application.properties.enc -out src/main/resources/application.properties
  -d
env:
  global:
    secure: "NqaVEEqd3gxocc1ppxeNRN7Xq5DGUtu8yZZnWC5DicGPY5TeCeW83Ne8c7yhPpzwUw+zzLFGihznmpY8O1tkHTwA0RimbtLXGUYXAMU6L3DmIeXgU74I5zsITNTLmItvup9HIk/zNaFXbk9wGxjEZvevZCuOr4D8AljDSt9hBIhvMIoaaehZBf9bk+rR1mW2jOVvemSgwmR8TshklHVKnxA+PaeTzD2j/L2rNItjHFhxhUl3kvz3jTBxRqMf5lnHOIHo398qwj7M3wdTORP8CLySmoZoX4yxwWjw2h00LelaHmfWuY/SxHngFNx5lts/tnVfkBg5OCPtfojJ6kMXmTizjH50bl80zuFuEpELqiziLk4RsMokdj4F9V5gFJpqEG1RMjLblPYSodocjXBOQYxBH7RwhphIDW+nLL2Uw5m1FrAkHvpdbSGnma27KytCDE5nlL8TW8NjvEbuLDDwBhJOzSXKGQJdhwVmFhM3hx2O2XoDxwgv1L6vhzrG6CEzpTnFYcgysSxxcmaX7a6RA04GsrNK36MfJcA/oh5jkwpKrLTFstJ4tNYHAVWpvpzu5KfsJS+LOLuoR81MYx4sZAOCuBCqySx/woBGznjcCpFLXWZMzMgecpB3i6kfPXWvUsC8nm56Z7f5OG7yqsHiOT/7Wa6Om+NN4hKZ1HikNw0="
